[package]

name = "comp_sci"
description = "Computer science with Rust."
version = "0.0.1"
authors = ["Kai Sellgren <kaisellgren@gmail.com>"]

[lib]

name = "comp_sci"
path = "src/lib.rs"

[dependencies]
bit-set = "0.4.0"
rand = "0.3.14"
rustc-serialize = "0.3.19"
